ORDER_API_URL = http://localhost:18081
ORDER_PROJECTION_URL = http://localhost:18082
ORDER_UI_URL = http://localhost:18080
KAFKA_BROKERS = localhost:19092
SCHEMA_REGISTRY_URL = http://localhost:18001
